name: Sysdig Scan and Send SBOM to Splunk

on:
  push:
    branches: [ main ]

jobs:
  scan_and_send_sbom:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: edsoncelio2024/demo-scan:latest
      SYSDIG_SECURE_HOST: app.us4.sysdig.com
      #SPLUNK_HEC_URL: https://splunk-host:8088/services/collector/event
      SYSDIG_API_TOKEN: ${{ secrets.SYSDIG_API_TOKEN }}
      #SPLUNK_HEC_TOKEN: ${{ secrets.SPLUNK_HEC_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Download Sysdig CLI Scanner
        run: |
          curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
          chmod +x sysdig-cli-scanner

      - name: Scan Image with Sysdig
        run: |
          IMAGE_ID=$(SECURE_API_TOKEN=$SYSDIG_API_TOKEN ./sysdig-cli-scanner \
            --apiurl https://$SYSDIG_SECURE_HOST \
            $IMAGE_NAME --policy sysdig-best-practices | grep 'ImageID:' | cut -d' ' -f2)
             echo "imageID=$IMAGE_ID" >> $GITHUB_OUTPUT

      - name: Wait for scan results to propagate (optional)
        run: sleep 30

      - name: Retrieve CycloneDX SBOM from Sysdig
        run: |
          curl -s -X GET \
            -H "Authorization: Bearer $SYSDIG_API_TOKEN" \
            "https://$SYSDIG_SECURE_HOST/secure/vulnerability/v1beta1/sboms?assetId=sha256:${{ steps.digest.outputs.imageID }}&assetType=container-image" \
            -o sbom.json

      - name: Cat SBOM
        run: |
          cat sbom.json
