name: Sysdig Scan and Send SBOM to Splunk

on:
  push:
    branches: [ main ]

jobs:
  scan_and_send_sbom:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: edsoncelio2024/demo-scan:latest
      SYSDIG_SECURE_HOST: app.us4.sysdig.com
      #SPLUNK_HEC_URL: https://splunk-host:8088/services/collector/event
      SYSDIG_API_TOKEN: ${{ secrets.SYSDIG_API_TOKEN }}
      #SPLUNK_HEC_TOKEN: ${{ secrets.SPLUNK_HEC_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Download Sysdig CLI Scanner
        run: |
          curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
          chmod +x sysdig-cli-scanner

      - name: Scan Image with Sysdig
        id: scan
        run: |
          SECURE_API_TOKEN=$SYSDIG_API_TOKEN ./sysdig-cli-scanner \
            --apiurl https://$SYSDIG_SECURE_HOST \
            $IMAGE_NAME

